[package]
name = "faery-operators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer = { version = "0.17.1", features = ["rayon", "nightly", "log"] }
faer-entity = "0.17.0"
